### ISSUE TITLE
live demo is non-functional

### ISSUE THREAD

**Issue by smithcommajoseph** [thegisdev/mapbox-gl-draw-rectangle-mode#3]
The live demo of this library is currently working. I suspect this can be fixed easily as there appears to be an issue with the mapboxgl accessToken being invalid.

Thanks,
Joseph

**Comment by erick-otenyo** [comment]
Hey @technicolorenvy .. Yea seems like the mapbox api token had issues. Here is a link to a fork with a working api key
https://bl.ocks.org/erick-otenyo/e22cefb2c69fb4d4db4c19d7778ed574
